// import { Navbar, Sidebar } from "@/components";
import { Navbar, Sidebar } from "@/components";
import "./globals.css";
import { Fira_Code } from "next/font/google";

const FiraCode = Fira_Code({
  weight: ["500"],
  // style: ["normal"],
  subsets: ["latin"],
  // display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={FiraCode.className}>
        <div className="flex my-16 px-24 gap-4 lg:flex-row md:flex-col sm:flex-col ">
          <div className=" p-4 text-base text-center bg-white/30 backdrop-blur-sm  dark:bg-dark-500 lg:col-span-3 rounded-2xl shado dark:shadow-custom-dark ">
            <Sidebar />
          </div>
          <div className="flex-1 backdrop-blur-sm bg-white/30 shadow-custom-light rounded-2xl ">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
